### ISSUE TITLE
SIGSEGV when getting help on parameters

### ISSUE THREAD

**Issue by gitbjo** [raoulh/mc-cli#2]
Hi,

I took the version available on: 
https://calaos.fr/mooltipass/tools/linux/ (old of 3 month)
Apparently you need to add version string somewhere so we can report against a specific version.

I get following when I run:
$ **moolticute-cli parameters --help**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4021e4]

goroutine 1 [running]:
panic(0x653ae0, 0xc4200100a0)
	C:/Go/src/runtime/panic.go:500 +0x1a1
main.checkLog()
	d:/gopath/src/github.com/raoulh/moolticute-cli/main.go:58 +0x24
main.main.func3(0xc42001c540)
	d:/gopath/src/github.com/raoulh/moolticute-cli/main.go:146 +0x14
github.com/jawher/mow%2ecli.(*Cmd).doInit(0xc42001c540, 0xa, 0x69e9c1)
	D:/gopath/src/github.com/jawher/mow.cli/commands.go:249 +0x385
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc42001c2a0, 0xc42000a3a0, 0x2, 0x2, 0xc420047e60, 0xc420047e60, 0xc42000b9e0, 0xc4200d3401, 0xc42000b9e0)
	D:/gopath/src/github.com/jawher/mow.cli/commands.go:449 +0x921
github.com/jawher/mow%2ecli.(*Cli).parse(0xc420047f28, 0xc42000a3a0, 0x2, 0x2, 0xc420047e60, 0xc420047e60, 0xc42000b9e0, 0x20, 0xc4200d3420)
	D:/gopath/src/github.com/jawher/mow.cli/cli.go:73 +0xa9
github.com/jawher/mow%2ecli.(*Cli).Run(0xc420047f28, 0xc42000a390, 0x3, 0x3, 0x3, 0xc4200d3420)
	D:/gopath/src/github.com/jawher/mow.cli/cli.go:102 +0x14a
main.main()
	d:/gopath/src/github.com/raoulh/moolticute-cli/main.go:149 +0x99e

My system is following: Ubuntu 12.04
Linux  3.2.0-124-generic #167-Ubuntu SMP Fri Mar 3 15:25:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by raoulh** [comment]
yes, parameters command is not yet implemented.
Help is welcome for doing it!

--
Raoul Hecky

2017-03-29 22:24 GMT+02:00 gitbjo <notifications@github.com>:
